import React, { Component } from 'react';

// const message = "This is a constant"
const count = 4

function isEven() {
  return count % 2 === 0 ? 'Even' : 'Odd'
}

export default class App extends Component {
  render = () => (
      <h4 className="bg-primary text-white text-center p-2 m-1">
        {/* { message } */}
        {/* Using a function in an expression, you must invoke it with 
            parentheses so that the result of the function is included 
            in the content generated by the component. */}
        Number of things: { isEven() }
      </h4>
  )
}


